## Functions and Collections Data Structures

### Overview:

In this module, learners move from writing one-off Python scripts to writing reusable, organized code. The focus is on three connected ideas:

1. Functions help us package logic so we can reuse it
2. Data structures help us organize information in useful ways
3. Pandas helps us apply that logic to tabular data

By the end of the session, learners should understand not just how to write functions, but why modular code matters in real analytical work.

---

## Learning Objectives

By the end of this module, you will be able to:

- Define and call custom Python functions
- Explain the role of parameters, arguments, and return values
- Use lists, dictionaries, tuples, and sets for structured data
- Write simple validation checks inside functions
- Use Pandas inside functions for small cleaning tasks
- Refactor repetitive logic into reusable code
- Save and version reusable scripts with Git and GitHub

---

1. Why modular code matters.

As your code gets longer, copy-pasting the same logic becomes difficult to maintain. Functions solve that problem.

In [1]:
quiz_scores = [80, 90, 100]

In [2]:
sum(quiz_scores), len(quiz_scores)

(270, 3)

In [3]:
quiz_average = sum(quiz_scores) / len(quiz_scores)

print(quiz_average)

90.0

In [4]:
exam_scores = [70, 85, 95]

In [5]:
exam_average = sum(exam_scores) / len(exam_scores)

print(exam_average)

83.33333333333333

Let's define a function so we can reuse the same code

`def` is the built-in Python keyword that tells Python we're making a function

In [6]:
def calculate_mean(values):
    return sum(values) / len(values)

In [7]:
# see our function in action with our quiz and exam scores
print(calculate_mean(quiz_scores))
print(calculate_mean(exam_scores))

90.0
83.33333333333333

In [8]:
calculate_mean(quiz_scores) == quiz_average

True

Now the logic is written once and reused many times.

Why this matters in real work
Functions help you:

* reduce repetition
* debug more easily
* test one piece of logic at a time
* make code easier for teammates to read
* scale workflows across multiple datasets

---

A function is a reusable block of code that performs a task.

Basic Syntax:

```
def greet_user(name):
    return f"Hello, {name}!"
```

### Key Terms
* Function definition: the code that creates the function
* Parameter: a variable listed in the function definition
* Argument: the actual value passed into the function
* Return value: the output the function sends back

In [9]:
def multiply_numbers(a, b):
    result = a*b
    return result

In [10]:
answer = multiply_numbers(4, 5)

answer

20

`a` and `b` are parameters

`4` and `5` are arguments

`20` is the return value

---

## 3. Important Function Concepts

---

### A. Functions Should Usually Do One Clear Thing

In [11]:
def calculate_total(price, quantity):
    return price * quantity

calculate_total(100, 2)

200

### B. Default Parameters

If we don't specify an argument for a parameter, the default parameter is the argument

In [12]:
def power_number(base, exponent=2):
    return base**exponent

In [13]:
power_number(10)

100

In [14]:
power_number(10, 3)

1000

In [15]:
power_number(exponent=2, base=10)

100

### C. Returning vs Printing

`return` sends a value back so it can be reused later.

In [18]:
def add_numbers(a, b):
    return a+b

x = add_numbers(2, 2)

This prints the result, but does not return it for reuse.

In [19]:
def add_numbers_print(a, b):
    print(a+b)

y = add_numbers_print(2, 2)

4

In [20]:
x

4

In [21]:
y

In [24]:
print(calculate_mean(exam_scores))


calculate_mean(quiz_scores)

83.33333333333333

90.0

### D. Docstrings

Docstrings explain what a function does.

In [28]:
def convert_to_upper(text):
    '''
    Look at this! I made a docstring!

    This function takes in some text and returns that text as uppercase
    
    '''
    return text.upper() # built-in python string method that upper cases strings

In [29]:
convert_to_upper("hello")

'HELLO'

In [30]:
# python built-in help function provides the docstring of functions and other stuff
help(convert_to_upper)

Help on function convert_to_upper in module __main__:

convert_to_upper(text)
    Look at this! I made a docstring!

    This function takes in some text and returns that text as uppercase

In [31]:
# help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.

### E. Variable Scope

Variables created inside a function stay inside that function unless returned.

In [39]:
def create_message(name):
    # message only exists as a variable INSIDE this function
    message = f"Welcome, {name}"
    return message

create_message("friend")

'Welcome, friend'

In [42]:
# Now message has been defined OUTSIDE of our function and Python can see that variable
message = create_message("Paul Atreides")

message

'Welcome, Paul Atreides'

## 4. Python Data Structures for Structured Data

Python data structures help us store and organize information.

### A. Lists

Lists store ordered, changeable collections.

In [43]:
# x = True
# y = 1.23456
# z = 1

scores = [88, 91, 79, 93]

type(scores)

list

Use lists when:

- order matters
- items may change
- duplicates are allowed

In [44]:
first_score = scores[0] # name_of_list[index_of_thing_to_grab]

first_score

88

In [45]:
second_score = scores[1]

second_score

91

In [46]:
# What happens when we try to an index that doesn't exist?
fifth_score = scores[4]

IndexError: list index out of range

### B. Dictionaries

Dictionaries store key-value pairs.

Use dictionaries when:

- you want labels for values
- you want to describe records clearly

In [47]:
student = {
    "name": "Ava", # key:value, comma separates key:value pairs
    "score": 95,
    "passed": True
}

In [49]:
# Dictionaries aren't indexed like lists
# To index a dictionary we do: 
# name_of_dictionary["key_we_want_to_access"]
student["name"]

'Ava'

### C. Tuples

Tuples are ordered collections that should not be changed.

Use tuples when:

- order matters
- the values should stay fixed

*Hint: Think of tuples as lists that can't be changed (immutable)*

In [50]:
# we make tuples with ()
coordinates = (40.7128, -74.0060)

In [51]:
def store_birthday(year, month, day):
    return (year, month, day)

In [52]:
random_birthday = store_birthday(1776, 7, 4)

random_birthday

(1776, 7, 4)

In [53]:
type(random_birthday)

tuple

In [54]:
year = random_birthday[0]

year

1776

### D. Sets

Sets store unique values.

```python
skills = {"python", "sql", "python", "excel"}
print(skills)
```

Use sets when:

- you want unique items only
- order does not matter

---

## 5. Combining Functions and Data Structures

Functions often accept data structures as inputs.

### Example: Calculate Average Score

In [55]:
def calculate_mean(values):
    return sum(values) / len(values)

calculate_mean(scores)

87.75

### Example: Pull a Value from a Dictionary

In [56]:
def get_student_score(student_record):
    return student_record["score"]

get_student_score(student)

95

### Example: Work with a List of Dictionaries

```python
records = [
    {"name": "Ava", "score": 95},
    {"name": "Luis", "score": 88},
    {"name": "Mina", "score": 91}
]

In [57]:
records = [
    {"name": "Ava", "score": 95},
    {"name": "Luis", "score": 88},
    {"name": "Mina", "score": 91}
]

In [60]:
names = []

for record in records:
    print(names)
    print(record["name"])
    names.append(record["name"])

[]
Ava
['Ava']
Luis
['Ava', 'Luis']
Mina

In [61]:
names

['Ava', 'Luis', 'Mina']

In [62]:
def get_names(records):
    names = []

    for record in records:
        names.append(record["name"])

    return names


get_names(records)

['Ava', 'Luis', 'Mina']

### Sidenote, you can loop over these data structures!

In [63]:
# Looping over a list
scores

[88, 91, 79, 93]

In [64]:
for score in scores:
    print(score)

88
91
79
93

In [65]:
# Dictionaries require specifying which part we're looping over
student

{'name': 'Ava', 'score': 95, 'passed': True}

In [66]:
for thing in student:
    print(thing)

name
score
passed

In [68]:
# to iterate through the key-value pairs of a dict, need to call .items() on the dictionary
for key, value in student.items():
    print(f"This is the key: {key}")
    print()
    print(f"This is the value: {value}")
    print()

This is the key: name

This is the value: Ava

This is the key: score

This is the value: 95

This is the key: passed

This is the value: True

---

## Sidenote 2, List Methods!

These allow us to do operations on our lists/modify them

In [98]:
numbers = [10, 20, 30]

numbers

[10, 20, 30]

In [100]:
# .append() adds an element to the end of our list
numbers.append(40)

numbers

[10, 20, 30, 40, 40]

In [101]:
# .extend() is when you want to add multiple itmes

numbers.extend([50, 60])

numbers

[10, 20, 30, 40, 40, 50, 60]

In [102]:
# .insert() adds element at a specific location
numbers.insert(1, 15)

In [103]:
numbers

[10, 15, 20, 30, 40, 40, 50, 60]

In [105]:
# .remove() removes an element from a list
numbers.remove(15)

numbers

[10, 20, 30, 40, 40, 50, 60]

In [106]:
# .pop() removes an element at an index (and returns it), defaults to last element
numbers.pop()

numbers

[10, 20, 30, 40, 40, 50]

In [107]:
# .sort() will sort the values in a list!
numbers.sort()

numbers

[10, 20, 30, 40, 40, 50]

---

## 6. Validation Inside Functions

Validation checks help catch problems early.

In [69]:
def calculate_mean(values):
    return sum(values) / len(values)

### Why validation matters

Validation helps you:

- catch bad inputs early
- produce clearer error messages
- make functions more reliable
- prevent silent mistakes in analysis

In [70]:
calculate_mean(scores)

87.75

In [73]:
# Python throws an error, it doesn't know how to handle student as the function input!
calculate_mean(student)

TypeError: values must be a list!

In [76]:
# re-write our calculate mean function with validation
def calculate_mean(values):
    if not isinstance(values, list):
        # we're checking to see that values is a list
        raise TypeError("values must be a list!")
        # we raise a TypeError, telling the user that the values input is not the right type
    if len(values) == 0:
        raise ValueError("values must not be an empty list!")
    return sum(values) / len(values)

In [77]:
len([])

0

In [82]:
# Checks if a variable is a certain data type then returns True or False
if not isinstance(student, dict):
    print("Not helps negate True")

In [83]:
# calculate_mean([])

## 7. Intro to Pandas for Function-Based Data Cleaning

Pandas is a Python library for working with tabular data.

In [ ]:
# !pip install pandas

In [84]:
# import pandas, with the alias
import pandas as pd

In [85]:
# define the dictionary
boring_dict = {
    "name": ["Ava", "Luis", "Mina", "Jordan"],
    "score": [95, None, 88, 91],
    "hours_studied": [10, 7, None, 8]
}

In [86]:
# now convert it to a dataframe
df = pd.DataFrame(boring_dict)

print(df)

     name  score  hours_studied
0     Ava   95.0           10.0
1    Luis    NaN            7.0
2    Mina   88.0            NaN
3  Jordan   91.0            8.0

In [87]:
# here are a few pandas methods to clean some data, then we'll put in a function
df.dropna()

     name  score  hours_studied
0     Ava   95.0           10.0
3  Jordan   91.0            8.0

In [89]:
# .dropna() drops ANY missing values from a dataframe
# BE AWARE, YOU CAN LOSE A LOT OF DATA WITH THIS
# if we wanted to save the dataframe after dropping missing rows
# df = df.dropna()

In [91]:
# we can fill missing values with .fillna()
# to access individual columns of a dataframe, df['name_of_col']
df['score'].fillna(df["score"].mean())

# took the score col, told pandas to fill in any missing data with the average score

0    95.000000
1    91.333333
2    88.000000
3    91.000000
Name: score, dtype: float64

In [93]:
# Add a dervided column
# to create a new column, df['name_of_new_column'] = values_for_new_column
df["passed"] = df["score"] >= 70

df

     name  score  hours_studied  passed
0     Ava   95.0           10.0    True
1    Luis    NaN            7.0   False
2    Mina   88.0            NaN    True
3  Jordan   91.0            8.0    True

In [96]:
# Now we'll put them all into functions
def fill_missing_scores(df):
    df["score"] = df["score"].fillna(df["score"].mean())
    return df

fill_missing_scores(df)

df

     name      score  hours_studied  passed
0     Ava  95.000000           10.0    True
1    Luis  91.333333            7.0   False
2    Mina  88.000000            NaN    True
3  Jordan  91.000000            8.0    True

---

## 8. Refactoring Repetitive Logic

One sign that you need a function is repeated code.

*Hint*: If you catch yourself writing the same logic 3+ times, that's a good indicator to refactor into a function!

In [108]:
# take our scores from two classes

math_scores = [80, 90, 100]
science_scores = [75, 85, 95]

In [109]:
# now manually calculate the average
math_average = sum(math_scores) / len(math_scores)
science_average = sum(science_scores) / len(science_scores)

In [110]:
# Now refactor into a fucntion

def calculate_mean(values):
    return sum(values) / len(values)

math_average = calculate_mean(math_scores)
science_average = calculate_mean(science_scores)

math_average, science_average

(90.0, 85.0)